### ISSUE TITLE
Beta 5 breaks HACs

### ISSUE THREAD

**Issue by noodlemctwoodle** [jimz011/homeassistant#21]
Updated to Beta 5 this morning and it appears to breaks HACs, reverted back to Beta 4 and HACs works as expected. 

```
2020-03-10 10:01:42 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/hacs/__init__.py", line 54, in async_setup
    await startup_wrapper_for_yaml()
  File "/config/custom_components/hacs/__init__.py", line 92, in startup_wrapper_for_yaml
    startup_result = await hacs_startup()
  File "/config/custom_components/hacs/__init__.py", line 121, in hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 244, in system_health_info
    return await hass.data[DOMAIN].async_get_info()
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 140, in async_get_info
    config = await self.async_load(False)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 154, in async_load
    self._load_config, force
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 173, in _load_config
    config = load_yaml(fname)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return yaml.load(conf_file, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 196, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 147, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 187, in _include_dir_merge_list_yaml
    loaded_yaml = load_yaml(fname)
  File "/config/custom_components/lovelace_gen/__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/config/lovelace/views/remote.yaml", line 34, in top-level template code
    - entity_tv: {{ _global.remote[0] }}
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'remote'
```

```
2020-03-10 10:14:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140561795783568] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 196, in send_with_error_handling
    result = await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 221, in websocket_lovelace_config
    return await hass.data[DOMAIN].async_load(msg["force"])
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 154, in async_load
    self._load_config, force
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 173, in _load_config
    config = load_yaml(fname)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return yaml.load(conf_file, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 196, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 147, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 187, in _include_dir_merge_list_yaml
    loaded_yaml = load_yaml(fname)
  File "/config/custom_components/lovelace_gen/__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/config/lovelace/views/remote.yaml", line 34, in top-level template code
    - entity_tv: {{ _global.remote[0] }}
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'remote'
```

**Comment by abeksis** [comment]
It's the same for me too, I've checked several times

**Comment by jimz011** [comment]
Known issue, will be fixed in the next beta sorry about this!

**Comment by jimz011** [comment]
should be fixed in beta 6 please let me know if it works
